package GUI;

import Implementacion.Vertice;

public class ModalSeleccionarFuente extends javax.swing.JDialog {

    private String ciudadOrigen;
    private String ciudadDestino;
    
    public static final int ORIGEN = 0;
    public static final int ORIGEN_DESTINO = 1;
    public static final int FUENTE = 2;

    /**
     * Creates new form ModalSeleccionarFuente
     */
    public ModalSeleccionarFuente(java.awt.Frame parent, boolean modal, int tipo) {
        super(parent, modal);
        initComponents();
        cargarCiudades(tipo);
    }

    private void cargarCiudades(int tipo) {
        GrafoChiapas grafo = new GrafoChiapas();
        comboBoxOrigen.removeAllItems();
        comboBoxDestino.removeAllItems();
        for (Vertice vertice : grafo.getCiudades()) {
            comboBoxOrigen.addItem(vertice.getNombre());
            comboBoxDestino.addItem(vertice.getNombre());
        }
        if (tipo == FUENTE) {
            lblOrigen.setText("Seleccionar Ciudad:");
            esconderDestino();
        } else if (tipo == ORIGEN) {
            esconderDestino();
        } else if (tipo == ORIGEN_DESTINO) {
            comboBoxDestino.setEnabled(true);
        }
    }

    private void esconderDestino() {
        comboBoxDestino.setEnabled(false);
        comboBoxDestino.setVisible(false);
        lblDestino.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        comboBoxOrigen = new javax.swing.JComboBox<>();
        lblOrigen = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        comboBoxDestino = new javax.swing.JComboBox<>();
        btnDestino = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        comboBoxOrigen.setBackground(new java.awt.Color(221, 221, 221));
        comboBoxOrigen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboBoxOrigen.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblOrigen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOrigen.setForeground(new java.awt.Color(0, 0, 0));
        lblOrigen.setText("Seleccionar Origen:");

        lblDestino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDestino.setForeground(new java.awt.Color(0, 0, 0));
        lblDestino.setText("Seleccionar Destino:");

        comboBoxDestino.setBackground(new java.awt.Color(221, 221, 221));
        comboBoxDestino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboBoxDestino.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDestino.setBackground(new java.awt.Color(134, 192, 160));
        btnDestino.setForeground(new java.awt.Color(0, 0, 0));
        btnDestino.setText("Buscar");
        btnDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestinoActionPerformed
        ciudadOrigen = comboBoxOrigen.getSelectedItem().toString();
        ciudadDestino = comboBoxDestino.getSelectedItem().toString();
        this.dispose();
    }//GEN-LAST:event_btnDestinoActionPerformed

    public void mostrar() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public String getCiudadOrigen() {
        return ciudadOrigen;
    }

    public String getCiudadDestino() {
        return ciudadDestino;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDestino;
    private javax.swing.JComboBox<String> comboBoxDestino;
    private javax.swing.JComboBox<String> comboBoxOrigen;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
